name: obfs code

permissions:
  contents: write

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  obfs_after_sync_upstream:
    name: Obfs after sync upstream repo
    runs-on: ubuntu-24.04

    steps:
      # Step 1: run a standard checkout action
      - name: Checkout target repo
        uses: actions/checkout@v3
        with:
          ssh-key: ${{  secrets.SSH_KEY }}

      - name: Setup Node.js environment 
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install javascript-obfuscator -g

      - name: Run obfs
        run: |
          git config --global user.email "bellong@vip.qq.com"
          git config --global user.name "bellong"
          cp -r _worker.js ../_worker.js
          git checkout --orphan obfs
          git rm -rf _worker.js
          javascript-obfuscator ../_worker.js --output _worker.js --compact true  --self-defending true --string-array-wrappers-count 5  --string-array-encoding base64 --split-strings true --split-strings-chunk-length 5 --rename-globals true --rename-properties true --transform-object-keys true --numbers-to-expressions true --simplify true --identifier-names-generator mangled --exclude UUID,ADD
          git add _worker.js
          git commit -m "obfs"
          git push origin obfs --force

      - name: Sync check
        if: failure()
        run: |
          echo "混淆代码失败，请检查！"
          exit 1